CREATE TABLE CALCULADORA_OPERACIONES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NUMERO1 NUMBER,
    NUMERO2 NUMBER,
    OPERACION VARCHAR2(20),
    RESULTADO NUMBER,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMIT;